name: VIDP ATFM Alert

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write  # allow committing seen.json
jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python vidp_alert.py

      - name: Commit seen.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add seen.json || true
          git diff --quiet || (git commit -m "Update seen.json [skip ci]" && git push)
